#!/bin/bash
gettime() {
time=$(date +'%a %b %d %H:%M:%S')
}

getpower() {
power=$(acpi | awk '{print $4}' | sed 's/,//g')
}
getvolume() {
volume=$(pamixer --get-volume-human)
}

getbrightness() {
	bright=$(light -G)
}

getmem() {
memused=$(free -m | grep Mem: | tail -1 | awk '{print $3 }')
memtotal=$(free -m | grep Mem: | tail -1 | awk '{print $2 }')
}

getupdates() {
updates=$(checkupdates | wc -l)
aur=$(aur repo -S -u -d revenge_repo | wc -l)
}

wmcheck() {
top=$(wmctrl -m | grep Name: | awk '{ print $2 }')
if [ "$top" = "Openbox" ]
then openboxworkspace
else getworkspace
fi
}

openwindows() {
	windows=$(echo $(wmctrl -l | awk '{print $2 " " $4}'))
}
openboxworkspace() {
	space=$(wmctrl -ld | grep "*" | tail -1 | awk '{print $10 }')
}
getworkspace() {
space=$(wmctrl -ld | grep "*" | tail -1 | awk '{print $9 }')
}

updatecheck() {
while true;
      do getupdates
      sleep 5
      done
}
      
getnetwork() {
	wifi=$(iwgetid -r)
}
output() {
	while true;
	do
	gettime
	getpower
	getvolume
	getmem
	wmcheck
	getnetwork
	getbrightness
	openwindows
echo " $space | $windows | $time | $power | $volume | $bright | $memused / $memtotal | $updates $aur | $wifi"	
	sleep 1
	done
}
bar() {
while true;
do 
getupdates
output | dzen2
sleep 1
done
}
#updatecheck
bar